# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xFP5Asv42Hgwf9jejKkhx_1dR7dJtnlV
"""

import json
import re
from collections import Counter

RESULT_PATH = "result.json"

with open(RESULT_PATH, "r", encoding="utf-8") as f:
    parser_output = json.load(f)

flows = parser_output.get("flows", [])
packets = parser_output.get("packets", [])
summary = parser_output.get("summary", {})

print("Summary:", summary)
print("Flows:", len(flows))
print("Packets:", len(packets))

if flows:
    print("First flow tags:", flows[0].get("tags", []))
    print("First flow observations:", flows[0].get("observations", []))

print("\nFirst 2 packets:")
for pkt in packets[:2]:
    print(json.dumps(pkt, indent=2, ensure_ascii=False))
    print("-" * 60)

MITRE_DB = [
    {
        "id": "T1021",
        "name": "Remote Services",
        "description": "Adversaries may use valid accounts to log into services designed to accept remote connections.",
        "tags": ["telnet_detected", "telnet_login_prompt", "telnet_password_prompt"],
        "keywords": ["login:", "password:", "last login", "telnet"],
        "attack_stage": "lateral movement / remote access"
    },
    {
        "id": "T1059",
        "name": "Command and Scripting Interpreter",
        "description": "Adversaries may abuse command and script interpreters to execute commands.",
        "tags": ["possible_command_execution"],
        "keywords": ["/bin/sh", "cmd.exe", "powershell", "/sbin/ping", "ping "],
        "attack_stage": "execution"
    },
    {
        "id": "T1046",
        "name": "Network Service Scanning",
        "description": "Adversaries may attempt to discover services running on remote systems.",
        "tags": ["tcp_syn"],
        "keywords": ["scan", "syn", "multiple ports", "sequential ports"],
        "attack_stage": "discovery / reconnaissance"
    },
    {
        "id": "T1190",
        "name": "Exploit Public-Facing Application",
        "description": "Adversaries may exploit vulnerabilities in public-facing applications.",
        "tags": ["possible_sql_injection", "possible_path_traversal", "suspicious_http_payload"],
        "keywords": ["union select", "or 1=1", "drop table", "../", "<script>", "sqlmap"],
        "attack_stage": "initial access / exploitation"
    },
    {
        "id": "T1071",
        "name": "Application Layer Protocol",
        "description": "Adversaries may use common application layer protocols for C2 or evasion.",
        "tags": ["dns_query", "tls_on_nonstandard_port", "possible_beaconing"],
        "keywords": ["dns", "beacon", "tls", "application protocol"],
        "attack_stage": "command and control"
    }
]

PROTOCOL_RISK_DB = [
    {
        "protocol_family": "telnet",
        "conditions": ["telnet_login_prompt", "telnet_password_prompt", "telnet_data"],
        "risk": "plaintext credential exposure",
        "severity": "high",
        "description": "Telnet session content is plaintext and may expose credentials and commands."
    },
    {
        "protocol_family": "http_attack",
        "conditions": ["possible_sql_injection", "possible_path_traversal", "suspicious_http_payload"],
        "risk": "web exploitation attempt",
        "severity": "high",
        "description": "Suspicious HTTP payload patterns may indicate injection or exploitation attempts."
    },
    {
        "protocol_family": "beaconing",
        "conditions": ["possible_beaconing"],
        "risk": "periodic communication pattern",
        "severity": "medium",
        "description": "Periodic communications may indicate automated beaconing."
    },
    {
        "protocol_family": "tls_nonstandard",
        "conditions": ["tls_on_nonstandard_port"],
        "risk": "encrypted traffic on non-standard port",
        "severity": "medium",
        "description": "TLS-like traffic on an unusual port may warrant investigation."
    }
]

PAYLOAD_INDICATOR_DB = [
    {
        "indicator": "login_prompt",
        "patterns": [r"login:"],
        "meaning": "login prompt observed",
        "severity": "medium"
    },
    {
        "indicator": "password_prompt",
        "patterns": [r"password:"],
        "meaning": "password prompt observed",
        "severity": "high"
    },
    {
        "indicator": "command_execution_ping",
        "patterns": [r"/sbin/ping", r"\bping\s+[A-Za-z0-9\.\-]+"],
        "meaning": "command execution evidence",
        "severity": "medium"
    },
    {
        "indicator": "sql_injection_string",
        "patterns": [r"union\s+select", r"or\s+1=1", r"drop\s+table"],
        "meaning": "SQL injection pattern",
        "severity": "high"
    },
    {
        "indicator": "path_traversal_string",
        "patterns": [r"\.\./"],
        "meaning": "path traversal pattern",
        "severity": "high"
    },
    {
        "indicator": "shell_indicator",
        "patterns": [r"/bin/sh", r"cmd\.exe", r"powershell"],
        "meaning": "shell execution indicator",
        "severity": "high"
    }
]

print("MITRE DB:", len(MITRE_DB))
print("Protocol Risk DB:", len(PROTOCOL_RISK_DB))
print("Payload Indicator DB:", len(PAYLOAD_INDICATOR_DB))

def get_packets_for_flow(flow, packets, all_flows):
    """
    当前样例里只有一个 flow，所以直接把所有 packets 归给它。
    如果以后 flow 正常拆分，再扩展更细粒度匹配逻辑。
    """
    if len(all_flows) == 1:
        return packets
    return packets


def dedup_keep_order(items):
    seen = set()
    out = []
    for x in items:
        key = str(x)
        if key not in seen:
            seen.add(key)
            out.append(x)
    return out

def clean_payload_previews(payload_previews):
    cleaned = []

    for p in payload_previews:
        if not p:
            continue

        text = str(p).strip()
        if not text:
            continue

        if re.search(r"[A-Za-z0-9]", text):
            printable_chars = sum(ch.isalnum() or ch in " .:/_-@$()[]=+" for ch in text)
            ratio = printable_chars / max(len(text), 1)

            if ratio >= 0.30:
                cleaned.append(text)

    seen = set()
    result = []
    for x in cleaned:
        if x not in seen:
            seen.add(x)
            result.append(x)

    return result


def clean_printable_strings(strings):
    cleaned = []

    for s in strings:
        if not s:
            continue

        text = str(s).strip()
        if len(text) < 3:
            continue

        if re.search(r"[A-Za-z0-9]", text):
            cleaned.append(text)

    seen = set()
    result = []
    for x in cleaned:
        if x not in seen:
            seen.add(x)
            result.append(x)

    return result

def build_event_profile(flow, packets_for_flow):
    flow_tags = flow.get("tags", [])
    flow_observations = flow.get("observations", [])
    intervals = flow.get("intervals", [])

    packet_tags = []
    packet_observations = []
    raw_payload_previews = []
    raw_printable_strings = []
    tcp_flags = []

    for pkt in packets_for_flow:
        packet_tags.extend(pkt.get("semantic_tags", []))
        packet_observations.extend(pkt.get("observations", []))

        preview = pkt.get("payload_preview", "")
        if preview and str(preview).strip():
            raw_payload_previews.append(preview)

        raw_printable_strings.extend(pkt.get("printable_strings", []))
        tcp_flags.extend(pkt.get("tcp_flags", []))

    flow_tags = dedup_keep_order(flow_tags)
    packet_tags = dedup_keep_order(packet_tags)
    all_tags = dedup_keep_order(flow_tags + packet_tags)
    flow_observations = dedup_keep_order(flow_observations)
    packet_observations = dedup_keep_order(packet_observations)
    tcp_flags = dedup_keep_order(tcp_flags)

    printable_strings = clean_printable_strings(raw_printable_strings)
    payload_previews = clean_payload_previews(raw_payload_previews)

    combined_text_parts = []
    combined_text_parts.extend(flow_observations)
    combined_text_parts.extend(packet_observations)
    combined_text_parts.extend(printable_strings)
    combined_text_parts.extend(payload_previews[:10])

    combined_text = "\n".join([x for x in combined_text_parts if x])

    profile = {
        "flow_key": flow.get("flow_key"),
        "packet_count": flow.get("packet_count", 0),
        "total_bytes": flow.get("total_bytes", 0),
        "flow_tags": flow_tags,
        "packet_tags": packet_tags,
        "all_tags": all_tags,
        "flow_observations": flow_observations,
        "packet_observations": packet_observations,
        "payload_previews": payload_previews,
        "printable_strings": printable_strings,
        "tcp_flags": tcp_flags,
        "intervals": intervals,
        "combined_text": combined_text
    }
    return profile

event_profiles = []

for flow in flows:
    pf = get_packets_for_flow(flow, packets, flows)
    event_profiles.append(build_event_profile(flow, pf))

print("Built event profiles:", len(event_profiles))

if event_profiles:
    print("\nAll tags:")
    print(event_profiles[0]["all_tags"])

    print("\nPrintable strings:")
    for s in event_profiles[0]["printable_strings"][:20]:
        print("-", s)

    print("\nCombined text preview:")
    print(event_profiles[0]["combined_text"][:2500])

def extract_payload_indicators(event_profile):
    text = event_profile["combined_text"].lower()
    tags = set(event_profile["all_tags"])

    indicators = {
        "credential_prompt": False,
        "plaintext_remote_login": False,
        "command_execution": False,
        "sql_injection": False,
        "path_traversal": False,
        "shell_execution": False,
        "beaconing_pattern": False,
        "telnet_session": False,
        "evidence_items": []
    }

    if "telnet_login_prompt" in tags or "telnet_password_prompt" in tags:
        indicators["credential_prompt"] = True
        indicators["evidence_items"].append("Credential prompt tags detected.")

    if "telnet_data" in tags:
        indicators["plaintext_remote_login"] = True
        indicators["telnet_session"] = True
        indicators["evidence_items"].append("Telnet application data detected.")

    if "possible_beaconing" in tags:
        indicators["beaconing_pattern"] = True
        indicators["evidence_items"].append("Beaconing tag detected.")

    if "possible_sql_injection" in tags or "suspicious_http_payload" in tags:
        indicators["sql_injection"] = True
        indicators["evidence_items"].append("SQL injection / suspicious HTTP tag detected.")

    if "possible_path_traversal" in tags:
        indicators["path_traversal"] = True
        indicators["evidence_items"].append("Path traversal tag detected.")

    if "possible_command_execution" in tags:
        indicators["command_execution"] = True
        indicators["shell_execution"] = True
        indicators["evidence_items"].append("Command execution tag detected.")

    text_rules = [
        ("credential_prompt", r"\blogin:\b", "Login prompt text observed."),
        ("credential_prompt", r"\bpassword:\b", "Password prompt text observed."),
        ("telnet_session", r"\blast login:", "Interactive login session evidence observed."),
        ("command_execution", r"/sbin/ping", "Command execution evidence: /sbin/ping"),
        ("command_execution", r"\bping\s+[A-Za-z0-9\.\-]+", "Ping command text observed."),
        ("sql_injection", r"union\s+select", "SQL injection text observed."),
        ("sql_injection", r"or\s+1=1", "SQL injection boolean pattern observed."),
        ("path_traversal", r"\.\./", "Path traversal text observed."),
        ("shell_execution", r"/bin/sh", "Shell execution text observed."),
        ("shell_execution", r"cmd\.exe", "cmd.exe text observed."),
        ("shell_execution", r"powershell", "PowerShell text observed."),
    ]

    for key, pattern, msg in text_rules:
        if re.search(pattern, text, flags=re.IGNORECASE):
            indicators[key] = True
            indicators["evidence_items"].append(msg)

    if indicators["shell_execution"]:
        indicators["command_execution"] = True

    return indicators

if event_profiles:
    sample_indicators = extract_payload_indicators(event_profiles[0])
    print(json.dumps(sample_indicators, indent=2, ensure_ascii=False))

def score_mitre_match(event_profile, indicators, mitre_item):
    score = 0
    evidence = []

    event_tags = set(event_profile["all_tags"])
    text = event_profile["combined_text"].lower()

    for tag in mitre_item["tags"]:
        if tag in event_tags:
            score += 3
            evidence.append(f"Tag match: {tag}")

    for kw in mitre_item["keywords"]:
        if kw.lower() in text:
            score += 2
            evidence.append(f"Keyword match: {kw}")

    if mitre_item["id"] == "T1021":
        if indicators["telnet_session"]:
            score += 3
            evidence.append("Indicator bonus: telnet session detected")
        if indicators["credential_prompt"]:
            score += 2
            evidence.append("Indicator bonus: credential prompt detected")
        if indicators["plaintext_remote_login"]:
            score += 2
            evidence.append("Indicator bonus: plaintext remote login evidence")

    if mitre_item["id"] == "T1059":
        if indicators["command_execution"]:
            score += 3
            evidence.append("Indicator bonus: command execution evidence")
        if indicators["shell_execution"]:
            score += 2
            evidence.append("Indicator bonus: shell execution evidence")

    if mitre_item["id"] == "T1190":
        if indicators["sql_injection"]:
            score += 3
            evidence.append("Indicator bonus: SQL injection evidence")
        if indicators["path_traversal"]:
            score += 3
            evidence.append("Indicator bonus: path traversal evidence")

    if mitre_item["id"] == "T1071":
        if indicators["beaconing_pattern"]:
            score += 3
            evidence.append("Indicator bonus: beaconing pattern detected")

    if mitre_item["id"] == "T1046":
        if "tcp_syn" in event_tags:
            score += 2
            evidence.append("Indicator bonus: SYN activity detected")

    return score, evidence


def retrieve_mitre_candidates(event_profile, indicators, mitre_db):
    candidates = []

    for item in mitre_db:
        score, evidence = score_mitre_match(event_profile, indicators, item)
        if score > 0:
            candidates.append({
                "id": item["id"],
                "name": item["name"],
                "description": item["description"],
                "attack_stage": item["attack_stage"],
                "score": score,
                "evidence": evidence
            })

    candidates.sort(key=lambda x: x["score"], reverse=True)
    return candidates

def retrieve_protocol_risks(event_profile, protocol_risk_db):
    tags = set(event_profile["all_tags"])
    risks = []

    for item in protocol_risk_db:
        matched = [cond for cond in item["conditions"] if cond in tags]
        if matched:
            risks.append({
                "protocol_family": item["protocol_family"],
                "risk": item["risk"],
                "severity": item["severity"],
                "description": item["description"],
                "matched_conditions": matched
            })

    return risks

def estimate_risk_level(mitre_candidates, protocol_risks, indicators):
    score = 0

    if mitre_candidates:
        score += mitre_candidates[0]["score"]

    for r in protocol_risks:
        if r["severity"] == "high":
            score += 3
        elif r["severity"] == "medium":
            score += 2
        else:
            score += 1

    if indicators["credential_prompt"]:
        score += 2
    if indicators["plaintext_remote_login"]:
        score += 2
    if indicators["command_execution"]:
        score += 2
    if indicators["sql_injection"]:
        score += 3
    if indicators["path_traversal"]:
        score += 3
    if indicators["beaconing_pattern"]:
        score += 2

    if score >= 12:
        return "high"
    elif score >= 6:
        return "medium"
    else:
        return "low"

def generate_reasoning(event_profile, indicators, mitre_candidates, protocol_risks):
    reasons = []

    if indicators["telnet_session"]:
        reasons.append("The traffic appears to include an interactive Telnet session.")
    if indicators["credential_prompt"]:
        reasons.append("Login and/or password prompts were observed, suggesting credential entry during the session.")
    if indicators["plaintext_remote_login"]:
        reasons.append("Human-readable application data suggests plaintext session content.")
    if indicators["command_execution"]:
        reasons.append("Command-like content was detected after session establishment.")
    if indicators["sql_injection"]:
        reasons.append("Payload content includes patterns associated with SQL injection.")
    if indicators["path_traversal"]:
        reasons.append("Payload content includes path traversal indicators.")
    if indicators["beaconing_pattern"]:
        reasons.append("Timing behavior suggests periodic communication that may indicate beaconing.")

    if mitre_candidates:
        top = mitre_candidates[0]
        reasons.append(f"The strongest ATT&CK mapping is {top['id']} - {top['name']}.")

    for r in protocol_risks[:2]:
        reasons.append(f"Protocol risk identified: {r['risk']}.")

    return " ".join(reasons)

def build_research_output(event_profile):
    indicators = extract_payload_indicators(event_profile)
    mitre_candidates = retrieve_mitre_candidates(event_profile, indicators, MITRE_DB)
    protocol_risks = retrieve_protocol_risks(event_profile, PROTOCOL_RISK_DB)
    risk_level = estimate_risk_level(mitre_candidates, protocol_risks, indicators)
    reasoning = generate_reasoning(event_profile, indicators, mitre_candidates, protocol_risks)

    evidence = []
    evidence.extend(indicators["evidence_items"])

    if mitre_candidates:
        evidence.extend(mitre_candidates[0]["evidence"])

    top_threat = mitre_candidates[0] if mitre_candidates else None

    output = {
        "flow_key": event_profile["flow_key"],
        "packet_count": event_profile["packet_count"],
        "total_bytes": event_profile["total_bytes"],
        "top_threat": top_threat,
        "threat_candidates": mitre_candidates[:5],
        "protocol_risks": protocol_risks,
        "risk_level": risk_level,
        "indicators": indicators,
        "evidence": evidence,
        "reasoning": reasoning,
        "recommended_focus": []
    }

    if indicators["credential_prompt"]:
        output["recommended_focus"].append("credential exposure")
    if indicators["plaintext_remote_login"]:
        output["recommended_focus"].append("plaintext remote access")
    if indicators["command_execution"]:
        output["recommended_focus"].append("post-login command execution")
    if indicators["sql_injection"] or indicators["path_traversal"]:
        output["recommended_focus"].append("application exploitation")
    if indicators["beaconing_pattern"]:
        output["recommended_focus"].append("periodic callback investigation")

    return output

research_outputs = [build_research_output(ep) for ep in event_profiles]

print(json.dumps(research_outputs[0], indent=2, ensure_ascii=False)[:4000])

for i, out in enumerate(research_outputs, start=1):
    print("=" * 80)
    print(f"Flow #{i}")
    print("Risk level:", out["risk_level"])

    if out["top_threat"]:
        print("Top threat:", out["top_threat"]["id"], "-", out["top_threat"]["name"])
        print("Top threat score:", out["top_threat"]["score"])
    else:
        print("Top threat: None")

    print("Recommended focus:", out["recommended_focus"])
    print("Reasoning:", out["reasoning"])

    print("Evidence:")
    for e in out["evidence"][:10]:
        print("-", e)

OUTPUT_PATH = "researcher_output_clean.json"

with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
    json.dump(research_outputs, f, indent=2, ensure_ascii=False)

print("Saved:", OUTPUT_PATH)

top_counter = Counter()

for out in research_outputs:
    if out["top_threat"]:
        top_counter[out["top_threat"]["name"]] += 1

print(top_counter)

